# GitHub Pages configuration
# This enables pretty URLs (removes .html extension)

# Enable pretty URLs without trailing slash
permalink: /:title

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Include files
include:
  - .htaccess

# Jekyll settings
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
excerpt_separator: "\n\n"
incremental: false

# GitHub Pages specific settings
github: [metadata]

# Prevent trailing slashes
trailing_slash: false
